services:
  app:
    volumes:
      - /mnt/d/code/demo/AIAgent/corporate_rag/src:/app/src
      - /mnt/d/code/demo/AIAgent/corporate_rag/tests:/app/tests
      - /mnt/d/code/demo/AIAgent/corporate_rag/test_docs:/app/test_docs

  nginx:
    volumes:
      - /mnt/d/code/demo/AIAgent/corporate_rag/deploy/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /mnt/d/code/demo/AIAgent/corporate_rag/deploy/nginx/html:/usr/share/nginx/html
