"""pg baseline

从零建出应用关系型库的 8 张表：7 张由 ORM metadata 生成，`chunks` 手写。
应用库需预先安装 vector 扩展（由超级用户执行，见 upgrade() 的前置断言）。

Revision ID: 0001
Revises:
Create Date: 2026-09-19 12:59:51.820045

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import context, op

# ORM 的 UTCDateTime 是自定义 TypeDecorator，autogenerate 会渲染成
# `src.infra.db.base.UTCDateTime(timezone=True)` —— 但该构造函数不接受 timezone
# 参数，迁移一执行就 TypeError；且迁移不宜 import 应用模型（模型会变，迁移要长期稳定）。
# 这里按其 impl 渲染为等价的 sa.DateTime(timezone=True)，DDL 完全相同。


# revision identifiers, used by Alembic.
revision: str = "0001"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """建出应用库的全部业务表与索引（从零建表）。"""
    # 扩展由超级用户预先创建（见 deploy/postgres/init/001_app_database.sh）。
    # 迁移账号是应用账号（非超级用户），建不了 vector —— vector 不是 trusted 扩展。
    # 这里显式断言，使失败可归因，而不是让下面的 vector(1024) 报难以定位的类型错误。
    # 离线模式（--sql）只生成脚本、不连库，无从查询扩展，故仅在联机执行时断言。
    if not context.is_offline_mode():
        conn = op.get_bind()
        installed = conn.execute(
            sa.text("SELECT 1 FROM pg_extension WHERE extname = 'vector'")
        ).scalar()
        if installed is None:
            raise RuntimeError(
                "应用库中未安装 vector 扩展，迁移无法创建 chunks.embedding。\n"
                "请由具备超级用户权限的账号先执行一次：\n"
                '    psql -d <应用库> -c "CREATE EXTENSION IF NOT EXISTS vector;"\n'
                "本地 dev 可用 compose 的 POSTGRES_USER（langfuse，超级用户）：\n"
                "    docker compose exec -T postgres psql -U langfuse -d corporate_rag "
                "-c 'CREATE EXTENSION IF NOT EXISTS vector;'"
            )
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "conversation_history",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("kb_id", sa.String(length=36), nullable=False),
        sa.Column(
            "role",
            sa.String(length=32),
            nullable=False,
            comment="user/assistant/system",
        ),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("sources", sa.Text(), nullable=True, comment="来源引用 JSON"),
        sa.Column("prompt_tokens", sa.Integer(), nullable=False),
        sa.Column("completion_tokens", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column(
            "model_name", sa.String(length=64), nullable=True, comment="模型名称"
        ),
        sa.Column(
            "process", sa.Text(), nullable=True, comment="过程事件JSON（历史回放）"
        ),
        sa.Column(
            "status",
            sa.String(length=16),
            nullable=False,
            comment="complete/interrupted",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_session",
        "conversation_history",
        ["session_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "document",
        sa.Column("kb_id", sa.String(length=36), nullable=False, comment="所属知识库"),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column(
            "file_type", sa.String(length=32), nullable=False, comment="文件类型"
        ),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column(
            "file_path", sa.String(length=1024), nullable=True, comment="MinIO 路径"
        ),
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="上传用户"),
        sa.Column("md5", sa.String(length=64), nullable=True, comment="文件 MD5"),
        sa.Column("hash", sa.String(length=64), nullable=True, comment="备用哈希"),
        sa.Column(
            "status",
            sa.String(length=32),
            nullable=False,
            comment="pending/processing/ready/failed",
        ),
        sa.Column("chunk_count", sa.Integer(), nullable=False),
        sa.Column("chunk_strategy", sa.String(length=64), nullable=True),
        sa.Column("processing_state", sa.String(length=64), nullable=True),
        sa.Column("processing_progress", sa.Integer(), nullable=False),
        sa.Column("processing_message", sa.String(length=512), nullable=True),
        sa.Column("error_msg", sa.String(length=1024), nullable=True),
        sa.Column("meta_info", sa.Text(), nullable=True, comment="JSON 扩展信息"),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_kb", "document", ["user_id", "kb_id"], unique=False)
    op.create_table(
        "eval_report",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("kb_id", sa.String(length=36), nullable=False),
        sa.Column("run_type", sa.String(length=64), nullable=False),
        sa.Column("qa_count", sa.Integer(), nullable=False),
        sa.Column("faithfulness", sa.Float(), nullable=False),
        sa.Column("answer_relevancy", sa.Float(), nullable=False),
        sa.Column("context_precision", sa.Float(), nullable=False),
        sa.Column("context_recall", sa.Float(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("report_path", sa.String(length=512), nullable=True),
        sa.Column("triggered_by", sa.String(length=64), nullable=True),
        sa.Column("detail_json", sa.Text(), nullable=True, comment="JSON 详细评估数据"),
        sa.Column("eval_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_kb_date", "eval_report", ["kb_id", "eval_date"], unique=False)
    op.create_table(
        "feedback",
        sa.Column(
            "session_id", sa.String(length=36), nullable=False, comment="会话 ID"
        ),
        sa.Column(
            "message_index", sa.Integer(), nullable=False, comment="会话内消息序号"
        ),
        sa.Column(
            "rating",
            sa.String(length=16),
            nullable=False,
            comment="评分: positive/negative",
        ),
        sa.Column("comment", sa.Text(), nullable=False, comment="用户评论"),
        sa.Column(
            "trace_id", sa.String(length=64), nullable=False, comment="全链路追踪 ID"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "knowledge_base",
        sa.Column("user_id", sa.String(length=36), nullable=False, comment="所属用户"),
        sa.Column("name", sa.String(length=256), nullable=False, comment="知识库名称"),
        sa.Column(
            "description", sa.String(length=1024), nullable=False, comment="描述"
        ),
        sa.Column("doc_count", sa.Integer(), nullable=False, comment="关联文档数"),
        sa.Column("is_deleted", sa.Integer(), nullable=False, comment="软删除标志"),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uk_user_kb"),
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("kb_id", sa.String(length=36), nullable=False),
        sa.Column(
            "agent",
            sa.String(length=64),
            nullable=False,
            comment="会话绑定的智能体预设名（ASCII slug；空=未绑定）",
        ),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("is_deleted", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_updated_at", "sessions", ["updated_at"], unique=False)
    op.create_index("idx_user", "sessions", ["user_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("account", sa.String(length=64), nullable=False, comment="登录账号"),
        sa.Column(
            "password", sa.String(length=256), nullable=False, comment="bcrypt 哈希"
        ),
        sa.Column(
            "token", sa.String(length=256), nullable=True, comment="当前登录 token"
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account"),
    )
    # ### end Alembic commands ###

    # --- 以下为手写增补：chunks 表（无 ORM 模型）---
    op.create_table(
        "chunks",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("kb_id", sa.Text(), nullable=False),
        sa.Column("doc_id", sa.Text(), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("chunk_total", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("content_seg", sa.Text(), nullable=False),
        sa.Column(
            "tsv",
            postgresql.TSVECTOR(),
            sa.Computed("to_tsvector('simple', content_seg)", persisted=True),
            nullable=True,
        ),
        sa.Column(
            "embedding",
            pgvector.sqlalchemy.Vector(1024),
            nullable=True,
            comment="DashScope text-embedding-v3",
        ),
        sa.Column("source", sa.Text(), nullable=False, server_default=sa.text("''")),
        sa.Column("page", sa.Integer(), nullable=False, server_default=sa.text("0")),
        sa.Column(
            "metadata",
            postgresql.JSONB(),
            nullable=False,
            server_default=sa.text("'{}'::jsonb"),
        ),
        sa.ForeignKeyConstraint(["kb_id"], ["knowledge_base.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "kb_id", "doc_id", "chunk_index", name="uq_chunks_kb_doc_idx"
        ),
    )
    op.create_index("ix_chunks_kb_id", "chunks", ["kb_id"])
    op.create_index("ix_chunks_doc_id", "chunks", ["doc_id"])
    op.create_index("ix_chunks_tsv", "chunks", ["tsv"], postgresql_using="gin")
    # 不建 HNSW：164 MB / 4 万分块规模下 kb_id btree + 精确扫描足够且召回精确，
    # 顺带避开「近似索引 + WHERE 过滤导致返回不足 k 条」。将来加是纯增量。
    #
    # 给 P2 的约定：chunks 的 metadata 列没有 ORM 模型（在 baseline 里手写）。
    # P2 若为 chunks 加 ORM 模型，属性名不能叫 metadata —— 那会覆盖 Base.metadata。
    # 要写成属性名与列名分离：
    #     extra: Mapped[dict] = mapped_column(
    #         "metadata", postgresql.JSONB(), nullable=False,
    #         server_default=sa.text("'{}'::jsonb"),
    #     )
    # 列名保持 metadata，不改 DDL。这条约定已记入 design.md D3。


def downgrade() -> None:
    """回滚本 baseline：删除全部业务表与索引（扩展不删，见下）。"""
    op.drop_table("chunks")
    # 不 DROP EXTENSION vector：同一实例的 Langfuse 库可能也在用它，
    # 删扩展会波及另一个 database。
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index("idx_user", table_name="sessions")
    op.drop_index("idx_updated_at", table_name="sessions")
    op.drop_table("sessions")
    op.drop_table("knowledge_base")
    op.drop_table("feedback")
    op.drop_index("idx_kb_date", table_name="eval_report")
    op.drop_table("eval_report")
    op.drop_index("idx_user_kb", table_name="document")
    op.drop_table("document")
    op.drop_index("idx_session", table_name="conversation_history")
    op.drop_table("conversation_history")
    # ### end Alembic commands ###
