"""init models

Revision ID: e6304ba3a9ef
Revises: 
Create Date: 2026-07-29 03:18:10.816550

"""
# ruff: noqa: F821
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e6304ba3a9ef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversation_history', 'id',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('conversation_history', 'session_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('conversation_history', 'kb_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('conversation_history', 'role',
               existing_type=mysql.ENUM('user', 'assistant'),
               type_=sa.String(length=32),
               comment='user/assistant/system',
               existing_nullable=False)
    op.alter_column('conversation_history', 'sources',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='来源引用 JSON',
               existing_nullable=True)
    op.alter_column('conversation_history', 'prompt_tokens',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'completion_tokens',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'total_tokens',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'model_name',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='模型名称',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('conversation_history', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_session'), table_name='conversation_history')
    op.add_column('document', sa.Column('md5', sa.String(length=64), nullable=True, comment='文件 MD5'))
    op.add_column('document', sa.Column('is_deleted', sa.Integer(), nullable=False))
    op.add_column('document', sa.Column('updated_at', src.infra.db.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('document', 'kb_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               comment='所属知识库',
               existing_nullable=False)
    op.alter_column('document', 'filename',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=False)
    op.alter_column('document', 'file_type',
               existing_type=mysql.VARCHAR(length=10),
               type_=sa.String(length=32),
               comment='文件类型',
               existing_nullable=False)
    op.alter_column('document', 'file_path',
               existing_type=mysql.VARCHAR(length=512),
               type_=sa.String(length=1024),
               comment='MinIO 路径',
               existing_nullable=True)
    op.alter_column('document', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               comment='上传用户',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('document', 'hash',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=64),
               comment='备用哈希',
               existing_nullable=True)
    op.alter_column('document', 'status',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=32),
               comment='pending/processing/ready/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('document', 'chunk_count',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('document', 'chunk_strategy',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=64),
               existing_nullable=True,
               existing_server_default=sa.text("'parent_child'"))
    op.alter_column('document', 'processing_state',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('document', 'processing_progress',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('document', 'processing_message',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('document', 'error_msg',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               existing_nullable=True)
    op.alter_column('document', 'meta_info',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='JSON 扩展信息',
               existing_nullable=True)
    op.alter_column('document', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('document', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_user_kb'), table_name='document')
    op.drop_constraint(op.f('document_ibfk_1'), 'document', type_='foreignkey')
    op.add_column('eval_report', sa.Column('created_at', src.infra.db.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('eval_report', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('eval_report', 'kb_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('eval_report', 'run_type',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.alter_column('eval_report', 'faithfulness',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('eval_report', 'answer_relevancy',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('eval_report', 'context_precision',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('eval_report', 'context_recall',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('eval_report', 'overall_score',
               existing_type=mysql.DECIMAL(precision=5, scale=4),
               type_=sa.Float(),
               nullable=False)
    op.alter_column('eval_report', 'passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('eval_report', 'triggered_by',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('eval_report', 'detail_json',
               existing_type=mysql.JSON(),
               type_=sa.Text(),
               comment='JSON 详细评估数据',
               existing_nullable=True)
    op.drop_index(op.f('idx_kb_date'), table_name='eval_report')
    op.drop_constraint(op.f('eval_report_ibfk_1'), 'eval_report', type_='foreignkey')
    op.add_column('knowledge_base', sa.Column('doc_count', sa.Integer(), nullable=False, comment='关联文档数'))
    op.add_column('knowledge_base', sa.Column('is_deleted', sa.Integer(), nullable=False, comment='软删除标志'))
    op.alter_column('knowledge_base', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               comment='所属用户',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('knowledge_base', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               comment='知识库名称',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'description',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=1024),
               nullable=False,
               comment='描述')
    op.alter_column('knowledge_base', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_column('knowledge_base', 'status')
    op.add_column('sessions', sa.Column('is_deleted', sa.Integer(), nullable=False))
    op.alter_column('sessions', 'user_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sessions', 'kb_id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sessions', 'title',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=256),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sessions', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.drop_index(op.f('idx_updated_at'), table_name='sessions')
    op.drop_index(op.f('idx_user'), table_name='sessions')
    op.add_column('users', sa.Column('updated_at', src.infra.db.base.UTCDateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'account',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=64),
               comment='登录账号',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=256),
               comment='bcrypt 哈希',
               existing_nullable=False)
    op.alter_column('users', 'token',
               existing_type=mysql.VARCHAR(length=64),
               type_=sa.String(length=256),
               comment='当前登录 token',
               existing_nullable=True)
    op.alter_column('users', 'id',
               existing_type=mysql.VARCHAR(length=36),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('users', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'token',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=64),
               comment=None,
               existing_comment='当前登录 token',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='bcrypt 哈希',
               existing_nullable=False)
    op.alter_column('users', 'account',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='登录账号',
               existing_nullable=False)
    op.drop_column('users', 'updated_at')
    op.create_index(op.f('idx_user'), 'sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_updated_at'), 'sessions', ['updated_at'], unique=False)
    op.alter_column('sessions', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('sessions', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('sessions', 'title',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sessions', 'kb_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('sessions', 'user_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_column('sessions', 'is_deleted')
    op.add_column('knowledge_base', sa.Column('status', mysql.VARCHAR(length=20), server_default=sa.text("'active'"), nullable=False))
    op.alter_column('knowledge_base', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('knowledge_base', 'description',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               nullable=True,
               comment=None,
               existing_comment='描述')
    op.alter_column('knowledge_base', 'name',
               existing_type=sa.String(length=256),
               type_=mysql.VARCHAR(length=255),
               comment=None,
               existing_comment='知识库名称',
               existing_nullable=False)
    op.alter_column('knowledge_base', 'user_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='所属用户',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.drop_column('knowledge_base', 'is_deleted')
    op.drop_column('knowledge_base', 'doc_count')
    op.create_foreign_key(op.f('eval_report_ibfk_1'), 'eval_report', 'knowledge_base', ['kb_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_kb_date'), 'eval_report', ['kb_id', 'eval_date'], unique=False)
    op.alter_column('eval_report', 'detail_json',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment=None,
               existing_comment='JSON 详细评估数据',
               existing_nullable=True)
    op.alter_column('eval_report', 'triggered_by',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=True)
    op.alter_column('eval_report', 'passed',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('eval_report', 'overall_score',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=4),
               nullable=True)
    op.alter_column('eval_report', 'context_recall',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=4),
               nullable=True)
    op.alter_column('eval_report', 'context_precision',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=4),
               nullable=True)
    op.alter_column('eval_report', 'answer_relevancy',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=4),
               nullable=True)
    op.alter_column('eval_report', 'faithfulness',
               existing_type=sa.Float(),
               type_=mysql.DECIMAL(precision=5, scale=4),
               nullable=True)
    op.alter_column('eval_report', 'run_type',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('eval_report', 'kb_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('eval_report', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_column('eval_report', 'created_at')
    op.create_foreign_key(op.f('document_ibfk_1'), 'document', 'knowledge_base', ['kb_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('idx_user_kb'), 'document', ['user_id', 'kb_id'], unique=False)
    op.alter_column('document', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('document', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('document', 'meta_info',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment=None,
               existing_comment='JSON 扩展信息',
               existing_nullable=True)
    op.alter_column('document', 'error_msg',
               existing_type=sa.String(length=1024),
               type_=mysql.TEXT(),
               existing_nullable=True)
    op.alter_column('document', 'processing_message',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('document', 'processing_progress',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('document', 'processing_state',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('document', 'chunk_strategy',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'parent_child'"))
    op.alter_column('document', 'chunk_count',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('document', 'status',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='pending/processing/ready/failed',
               existing_nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('document', 'hash',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=32),
               comment=None,
               existing_comment='备用哈希',
               existing_nullable=True)
    op.alter_column('document', 'user_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='上传用户',
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('document', 'file_path',
               existing_type=sa.String(length=1024),
               type_=mysql.VARCHAR(length=512),
               comment=None,
               existing_comment='MinIO 路径',
               existing_nullable=True)
    op.alter_column('document', 'file_type',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=10),
               comment=None,
               existing_comment='文件类型',
               existing_nullable=False)
    op.alter_column('document', 'filename',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('document', 'kb_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               comment=None,
               existing_comment='所属知识库',
               existing_nullable=False)
    op.drop_column('document', 'updated_at')
    op.drop_column('document', 'is_deleted')
    op.drop_column('document', 'md5')
    op.create_index(op.f('idx_session'), 'conversation_history', ['session_id', 'created_at'], unique=False)
    op.alter_column('conversation_history', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('conversation_history', 'model_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=100),
               comment=None,
               existing_comment='模型名称',
               existing_nullable=True,
               existing_server_default=sa.text("''"))
    op.alter_column('conversation_history', 'total_tokens',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'completion_tokens',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'prompt_tokens',
               existing_type=mysql.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('conversation_history', 'sources',
               existing_type=sa.Text(),
               type_=mysql.JSON(),
               comment=None,
               existing_comment='来源引用 JSON',
               existing_nullable=True)
    op.alter_column('conversation_history', 'role',
               existing_type=sa.String(length=32),
               type_=mysql.ENUM('user', 'assistant'),
               comment=None,
               existing_comment='user/assistant/system',
               existing_nullable=False)
    op.alter_column('conversation_history', 'kb_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False,
               existing_server_default=sa.text("''"))
    op.alter_column('conversation_history', 'session_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=36),
               existing_nullable=False)
    op.alter_column('conversation_history', 'id',
               existing_type=sa.String(length=32),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
